# -*- coding: utf-8 -*-
"""Kelompok3_Kelas09_CS2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSqywM1iMaV9ALuKGhGP5txoZlioJLo5
"""

#Link youtube: https://youtu.be/yR0A4MfL1Ok
#Kelompok 3
#Muhammad Shofwan Azzam (2506547084) data_banjir & class
#⁠Kanissa Phoebe Prameswari (2506544441) siaga function
#Gabriella Priscillia Agustin (2506549240) masukkan_data function
#Nadzira Aqila Daviana (2506548124) dataframe & pemindahan function

#Import library panda untuk dipakai saat membuat dataframe
import pandas as pd

#Buat list riwayat data banjir dan list untuk data banjir baru
data_banjir = [
    {
        "Tahun": 2015,
        "Curah_hujan (mm/hari)": 277,
        "Tinggi_air (cm)": 371,
        "Lama_banjir (hari)": 3,
        "Level_siaga": "Siaga 1",
        "Deskripsi": "SANGAT KRITIS. Proses evakuasi harus sudah dilakukan."
    },
    {
        "Tahun": 2016,
        "Curah_hujan (mm/hari)": 125,
        "Tinggi_air (cm)": 447,
        "Lama_banjir (hari)": 1,
        "Level_siaga": "Siaga 1",
        "Deskripsi": "SANGAT KRITIS. Proses evakuasi harus sudah dilakukan."
    },
    {
        "Tahun": 2020,
        "Curah_hujan (mm/hari)": 377,
        "Tinggi_air (cm)": 428,
        "Lama_banjir (hari)": 4,
        "Level_siaga": "Siaga 1",
        "Deskripsi": "SANGAT KRITIS. Proses evakuasi harus sudah dilakukan."
    },
    {
        "Tahun": 2025,
        "Curah_hujan (mm/hari)": 232,
        "Tinggi_air (cm)": 312,
        "Lama_banjir (hari)": 3,
        "Level_siaga": "Siaga 1",
        "Deskripsi": "SANGAT KRITIS. Proses evakuasi harus sudah dilakukan."
    }
]

data_banjir_baru = []

#Class untuk input data dan masukkan ke list untuk data baru
class input_data:
  def __init__(self, tahun, curah_hujan, tinggi_air, lama_banjir):
    self.tahun = tahun
    self.curah_hujan = curah_hujan
    self.tinggi_air = tinggi_air
    self.lama_banjir = lama_banjir

  #Function untuk input data baru
  def masukkan_data():
    question = input("Apakah anda ingin memasukkan data? (ya/tidak): ")
    while question.lower() == "ya":
        input_tahun = int(input("Masukkan tahun: "))
        input_curah_hujan = int(input("Masukkan curah hujan (mm/hari): "))
        input_tinggi_air = int(input("Masukkan tinggi air (cm): "))
        input_lama_banjir = int(input("Masukkan lama banjir (hari): "))
        question = input("\nApakah anda ingin memasukkan data lagi? (ya/tidak): ")

        data_banjir_baru.append({
            "Tahun": input_tahun,
            "Curah_hujan (mm/hari)": input_curah_hujan,
            "Tinggi_air (cm)": input_tinggi_air,
            "Lama_banjir (hari)": input_lama_banjir
        })

    return data_banjir, data_banjir_baru

  #Function untuk mengklasifikasikan level siaga
  def level_siaga():
    for data in data_banjir_baru:
      curah_hujan = data["Curah_hujan (mm/hari)"]
      tinggi_air = data["Tinggi_air (cm)"]

      if curah_hujan < 100 and tinggi_air < 80:
        siaga_level = "Siaga 4"
      elif curah_hujan >= 100 and tinggi_air >= 80 and tinggi_air <= 149:
        siaga_level = "Siaga 3"
      elif curah_hujan >= 100 and tinggi_air >= 150 and tinggi_air <= 199:
        siaga_level = "Siaga 2"
      elif curah_hujan >= 150 and tinggi_air >= 200:
        siaga_level = "Siaga 1"
      else:
        siaga_level = "Keadaan tidak memenuhi kriteria Siaga."

      data["Level_siaga"] = siaga_level

      if data["Level_siaga"] == "Siaga 4":
        send_alert = "BATAS NORMAL. Belum ada tanda-tanda banjir besar, Masyarakat dihimbau untuk memantau kondisi lingkungan."
      elif data["Level_siaga"] == "Siaga 3":
        send_alert = "MULAI WASPADA. Masyarakat mulai berhati-hati dan bersiap, sudah ada resiko banjir."
      elif data["Level_siaga"] == "Siaga 2":
        send_alert = "KRITIS. Proses evakuasi dimulai dan warga harus bersiap untuk evakuasi."
      elif data["Level_siaga"] == "Siaga 1":
        send_alert = "SANGAT KRITIS. Proses evakuasi harus sudah dilakukan."
      else:
        send_alert = "Keadaan tidak memenuhi kriteria Siaga."

      data["Deskripsi"] = send_alert

#Memanggil class
input_data.masukkan_data()
input_data.level_siaga()

#Membuat dataframe menggunakan fungsi dari library panda
df_data_banjir = pd.DataFrame(data_banjir)
df_data_banjir.index = df_data_banjir.index + 1
df_data_banjir_baru = pd.DataFrame(data_banjir_baru)
df_data_banjir_baru.index = df_data_banjir_baru.index + 1
print("\n")
display(df_data_banjir.style.set_caption("Riwayat data hujan, tinggi air, dan lama banjir"))
print("\n")
display(df_data_banjir_baru.style.set_caption("Data baru"))
print("\n")

#Function bila user ingin memindahkan data baru ke data riwayat banjir
def pemindahan():
    question2 = input("\nApakah anda memindahkan data ke riwayat banjir? (ya/tidak): ")
    if question2.lower() == "ya":
      data_banjir.extend(data_banjir_baru)
      data_banjir_baru.clear()
      data_banjir_baru.append({
        "Tahun": 0,
        "Curah_hujan (mm/hari)": 0,
        "Tinggi_air (cm)": 0,
        "Lama_banjir (hari)": 0,
        "Level_siaga": "-",
        "Deskripsi": "-"
      })
      print("Data berhasil dipindahkan\n")
    else:
      print("Data tidak dipindahkan\n")

#Memanggil function dan memunculkan kembali dataframe yang sudah di-update
pemindahan()
df_data_banjir = pd.DataFrame(data_banjir)
df_data_banjir.index = df_data_banjir.index + 1
print("\n")
df_data_banjir_baru = pd.DataFrame(data_banjir_baru)
df_data_banjir_baru.index = df_data_banjir_baru.index + 1
print("\n")
display(df_data_banjir.style.set_caption("Riwayat data hujan, tinggi air, dan lama banjir"))
display(df_data_banjir_baru.style.set_caption("Data baru"))